package metier;
// Generated 5 nov. 2015 15:21:55 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Activite generated by hbm2java
 */
@Entity
@Table(name = "activite", catalog = "cerisaie")
@XmlRootElement(name = "Activite")
public class Activite implements java.io.Serializable {

	private Integer idActivite;
	private Sejour sejour;
	private Sport sport;
	private Date dateJour;
	private Integer nbloc;

	public Activite() {
	}

	public Activite(Sejour sejour, Sport sport, Date dateJour) {
		this.sejour = sejour;
		this.sport = sport;
		this.dateJour = dateJour;
	}

	public Activite(Sejour sejour, Sport sport, Date dateJour, Integer nbloc) {
		this.sejour = sejour;
		this.sport = sport;
		this.dateJour = dateJour;
		this.nbloc = nbloc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdActivite", unique = true, nullable = false)
	public Integer getIdActivite() {
		return this.idActivite;
	}

	public void setIdActivite(Integer idActivite) {
		this.idActivite = idActivite;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "NumSej", nullable = false)
	public Sejour getSejour() {
		return this.sejour;
	}

	public void setSejour(Sejour sejour) {
		this.sejour = sejour;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CodeSport", nullable = false)
	public Sport getSport() {
		return this.sport;
	}

	public void setSport(Sport sport) {
		this.sport = sport;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateJour", nullable = false, length = 0)
	public Date getDateJour() {
		return this.dateJour;
	}

	public void setDateJour(Date dateJour) {
		this.dateJour = dateJour;
	}

	@Column(name = "NBLOC")
	public Integer getNbloc() {
		return this.nbloc;
	}

	public void setNbloc(Integer nbloc) {
		this.nbloc = nbloc;
	}

}
