package metier;
// Generated 5 nov. 2015 15:21:55 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "cerisaie")
@XmlRootElement(name = "Client")
public class Client implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer numCli;
	private String nomCli;
	private String adrRueCli;
	private String cpCli;
	private String villeCli;
	private String pieceCli;
	private String numPieceCli;
	private Set<Sejour> sejours = new HashSet<Sejour>(0);

	public Client() {
	}

	public Client(String nomCli, String adrRueCli, String cpCli, String villeCli, String pieceCli, String numPieceCli,
			Set<Sejour> sejours) {
		this.nomCli = nomCli;
		this.adrRueCli = adrRueCli;
		this.cpCli = cpCli;
		this.villeCli = villeCli;
		this.pieceCli = pieceCli;
		this.numPieceCli = numPieceCli;
		this.sejours = sejours;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "NumCli", unique = true, nullable = false)
	public Integer getNumCli() {
		return this.numCli;
	}

	public void setNumCli(Integer numCli) {
		this.numCli = numCli;
	}

	@Column(name = "NomCli", length = 30)
	public String getNomCli() {
		return this.nomCli;
	}

	public void setNomCli(String nomCli) {
		this.nomCli = nomCli;
	}

	@Column(name = "AdrRueCli", length = 40)
	public String getAdrRueCli() {
		return this.adrRueCli;
	}

	@Override
	public String toString() {
		return "Client [numCli=" + numCli + ", nomCli=" + nomCli + ", adrRueCli=" + adrRueCli + ", cpCli=" + cpCli
				+ ", villeCli=" + villeCli + ", pieceCli=" + pieceCli + ", numPieceCli=" + numPieceCli + ", sejours="
				+ sejours + "]";
	}

	public void setAdrRueCli(String adrRueCli) {
		this.adrRueCli = adrRueCli;
	}

	@Column(name = "CpCli", length = 5)
	public String getCpCli() {
		return this.cpCli;
	}

	public void setCpCli(String cpCli) {
		this.cpCli = cpCli;
	}

	@Column(name = "VilleCli", length = 40)
	public String getVilleCli() {
		return this.villeCli;
	}

	public void setVilleCli(String villeCli) {
		this.villeCli = villeCli;
	}

	@Column(name = "PieceCli", length = 10)
	public String getPieceCli() {
		return this.pieceCli;
	}

	public void setPieceCli(String pieceCli) {
		this.pieceCli = pieceCli;
	}

	@Column(name = "NumPieceCli", length = 20)
	public String getNumPieceCli() {
		return this.numPieceCli;
	}

	public void setNumPieceCli(String numPieceCli) {
		this.numPieceCli = numPieceCli;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Sejour> getSejours() {
		return this.sejours;
	}

	public void setSejours(Set<Sejour> sejours) {
		this.sejours = sejours;
	}

}
