package metier;
// Generated 5 nov. 2015 15:21:55 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Emplacement generated by hbm2java
 */
@Entity
@Table(name = "emplacement", catalog = "cerisaie")
@XmlRootElement(name = "Emplacement")
public class Emplacement implements java.io.Serializable {

	private Integer numEmpl;
	private TypeEmplacement typeEmplacement;
	private float surfaceEmpl;
	private int nbPersMaxEmpl;
	private Set<Sejour> sejours = new HashSet<Sejour>(0);

	public Emplacement() {
	}

	public Emplacement(TypeEmplacement typeEmplacement, float surfaceEmpl, int nbPersMaxEmpl) {
		this.typeEmplacement = typeEmplacement;
		this.surfaceEmpl = surfaceEmpl;
		this.nbPersMaxEmpl = nbPersMaxEmpl;
	}

	public Emplacement(TypeEmplacement typeEmplacement, float surfaceEmpl, int nbPersMaxEmpl, Set<Sejour> sejours) {
		this.typeEmplacement = typeEmplacement;
		this.surfaceEmpl = surfaceEmpl;
		this.nbPersMaxEmpl = nbPersMaxEmpl;
		this.sejours = sejours;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NumEmpl", unique = true, nullable = false)
	public Integer getNumEmpl() {
		return this.numEmpl;
	}

	public void setNumEmpl(Integer numEmpl) {
		this.numEmpl = numEmpl;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodeTypeE", nullable = false)
	public TypeEmplacement getTypeEmplacement() {
		return this.typeEmplacement;
	}

	public void setTypeEmplacement(TypeEmplacement typeEmplacement) {
		this.typeEmplacement = typeEmplacement;
	}

	@Column(name = "SurfaceEmpl", nullable = false, precision = 12, scale = 0)
	public float getSurfaceEmpl() {
		return this.surfaceEmpl;
	}

	public void setSurfaceEmpl(float surfaceEmpl) {
		this.surfaceEmpl = surfaceEmpl;
	}

	@Column(name = "NbPersMaxEmpl", nullable = false)
	public int getNbPersMaxEmpl() {
		return this.nbPersMaxEmpl;
	}

	public void setNbPersMaxEmpl(int nbPersMaxEmpl) {
		this.nbPersMaxEmpl = nbPersMaxEmpl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emplacement")
	public Set<Sejour> getSejours() {
		return this.sejours;
	}

	public void setSejours(Set<Sejour> sejours) {
		this.sejours = sejours;
	}

}
