package metier;
// Generated 5 nov. 2015 15:21:55 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Sport generated by hbm2java
 */
@Entity
@Table(name = "sport", catalog = "cerisaie")
@XmlRootElement(name = "Sport")
public class Sport implements java.io.Serializable {

	private Integer codeSport;
	private String libelleSport;
	private String uniteTpsSport;
	private float tarifUnite;
	private List<Activite> activites = new ArrayList<Activite>();

	public Sport() {
	}

	public Sport(String libelleSport, String uniteTpsSport, float tarifUnite) {
		this.libelleSport = libelleSport;
		this.uniteTpsSport = uniteTpsSport;
		this.tarifUnite = tarifUnite;
	}

	public Sport(String libelleSport, String uniteTpsSport, float tarifUnite, List<Activite> activites) {
		this.libelleSport = libelleSport;
		this.uniteTpsSport = uniteTpsSport;
		this.tarifUnite = tarifUnite;
		this.activites = activites;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CodeSport", unique = true, nullable = false)
	public Integer getCodeSport() {
		return this.codeSport;
	}

	public void setCodeSport(Integer codeSport) {
		this.codeSport = codeSport;
	}

	@Column(name = "LibelleSport", nullable = false, length = 10)
	public String getLibelleSport() {
		return this.libelleSport;
	}

	public void setLibelleSport(String libelleSport) {
		this.libelleSport = libelleSport;
	}

	@Column(name = "UniteTpsSport", nullable = false, length = 10)
	public String getUniteTpsSport() {
		return this.uniteTpsSport;
	}

	public void setUniteTpsSport(String uniteTpsSport) {
		this.uniteTpsSport = uniteTpsSport;
	}

	@Column(name = "TarifUnite", nullable = false, precision = 12, scale = 0)
	public float getTarifUnite() {
		return this.tarifUnite;
	}

	public void setTarifUnite(float tarifUnite) {
		this.tarifUnite = tarifUnite;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sport")
	public List<Activite> getActivites() {
		return this.activites;
	}

	public void setActivites(List<Activite> activites) {
		this.activites = activites;
	}

}
